# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Farmaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Itk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Rel_Biblio_Rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interacciones.Bibliografia')),
            ],
        ),
        migrations.CreateModel(
            name='Rel_Itk_Far',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=128)),
                ('efecto', models.CharField(max_length=128)),
                ('mecanismo', models.CharField(max_length=128)),
                ('recomendacion', models.CharField(max_length=128)),
                ('farmaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmacos', to='interacciones.Farmaco')),
                ('itk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itks', to='interacciones.Itk')),
            ],
        ),
        migrations.AddField(
            model_name='rel_biblio_rel',
            name='rel_itk_far',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interacciones.Rel_Itk_Far'),
        ),
    ]
