# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interacciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmaco',
            name='mecanismo',
        ),
        migrations.AddField(
            model_name='rel_itk_far',
            name='mecanismo',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
