# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interacciones', '0002_auto_20160704_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmaco',
            name='grupo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='interacciones.Grupo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rel_itk_far',
            name='farmaco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmacos', to='interacciones.Farmaco'),
        ),
        migrations.AlterField(
            model_name='rel_itk_far',
            name='itk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itks', to='interacciones.Itk'),
        ),
    ]
