# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interacciones', '0003_auto_20160704_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmaco',
            name='grupo',
        ),
    ]
